apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mirror-test-aug27 
  description: Secure Supply Chain Example for Code Generation Application example that generate code in countless programming languages.   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used rhtap-gitops as the grouping
    argocd/app-selector: rhtap/gitops=mirror-test-aug27  
    janus-idp.io/tekton: mirror-test-aug27 
    backstage.io/kubernetes-id: mirror-test-aug27 
    backstage.io/techdocs-ref: dir:. 
    quay.io/repository-slug: jdubrick-ai/mirror-test-aug27
  tags: ["ai", "llamacpp", "vllm", "python"] 
spec:
  type: service
  owner: user:guest 
  lifecycle: experimental
 